### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Adam-JR** [Adam-JR/mybooks#16]
- [x] Add messages to login after incorrect login or password
- [x] Move id from template forms to edit view
- [ ] Add image file to book and author
- [ ] Change author list style
- [ ] Change author details style
- [ ] Change book list style
- [ ] Change book details style
